### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by szepeviktor** [Sanakan8472/copy-dialog-lunar-lander#3]
Hello! I have no large file to copy :)

Please consider introducing standalone mode with fake "terrain".
Thank you!

**Comment by PixelHir** [comment]
`fsutil file createnew file 50000000`

now you have a large file :)

**Comment by Sanakan8472** [comment]
While I understand your wish to play at any time without requiring a file, removing the need for a copy dialog would put my app into an identity crisis.
As an alternative solution, instead of copying a big file, copy a small file very, very slowly. I can recommend [harder drive](https://www.youtube.com/watch?v=JcJSW7Rprio) as a source for inspiration.

**Comment by szepeviktor** [comment]
"Thank" you!
You've just killed 7 000 000 brin cells of mine by making me watch that video 🙃
